// Generated by gencpp from file rns_msgs/AnnotationRequest.msg
// DO NOT EDIT!


#ifndef RNS_MSGS_MESSAGE_ANNOTATIONREQUEST_H
#define RNS_MSGS_MESSAGE_ANNOTATIONREQUEST_H

#include <ros/service_traits.h>


#include <rns_msgs/AnnotationRequestRequest.h>
#include <rns_msgs/AnnotationRequestResponse.h>


namespace rns_msgs
{

struct AnnotationRequest
{

typedef AnnotationRequestRequest Request;
typedef AnnotationRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnnotationRequest
} // namespace rns_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rns_msgs::AnnotationRequest > {
  static const char* value()
  {
    return "dd246964568ef4be2c20b91dcd74fd2a";
  }

  static const char* value(const ::rns_msgs::AnnotationRequest&) { return value(); }
};

template<>
struct DataType< ::rns_msgs::AnnotationRequest > {
  static const char* value()
  {
    return "rns_msgs/AnnotationRequest";
  }

  static const char* value(const ::rns_msgs::AnnotationRequest&) { return value(); }
};


// service_traits::MD5Sum< ::rns_msgs::AnnotationRequestRequest> should match 
// service_traits::MD5Sum< ::rns_msgs::AnnotationRequest > 
template<>
struct MD5Sum< ::rns_msgs::AnnotationRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::AnnotationRequest >::value();
  }
  static const char* value(const ::rns_msgs::AnnotationRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::AnnotationRequestRequest> should match 
// service_traits::DataType< ::rns_msgs::AnnotationRequest > 
template<>
struct DataType< ::rns_msgs::AnnotationRequestRequest>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::AnnotationRequest >::value();
  }
  static const char* value(const ::rns_msgs::AnnotationRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rns_msgs::AnnotationRequestResponse> should match 
// service_traits::MD5Sum< ::rns_msgs::AnnotationRequest > 
template<>
struct MD5Sum< ::rns_msgs::AnnotationRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::AnnotationRequest >::value();
  }
  static const char* value(const ::rns_msgs::AnnotationRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::AnnotationRequestResponse> should match 
// service_traits::DataType< ::rns_msgs::AnnotationRequest > 
template<>
struct DataType< ::rns_msgs::AnnotationRequestResponse>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::AnnotationRequest >::value();
  }
  static const char* value(const ::rns_msgs::AnnotationRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RNS_MSGS_MESSAGE_ANNOTATIONREQUEST_H
