// Generated by gencpp from file rns_msgs/AnnotationModify.msg
// DO NOT EDIT!


#ifndef RNS_MSGS_MESSAGE_ANNOTATIONMODIFY_H
#define RNS_MSGS_MESSAGE_ANNOTATIONMODIFY_H

#include <ros/service_traits.h>


#include <rns_msgs/AnnotationModifyRequest.h>
#include <rns_msgs/AnnotationModifyResponse.h>


namespace rns_msgs
{

struct AnnotationModify
{

typedef AnnotationModifyRequest Request;
typedef AnnotationModifyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AnnotationModify
} // namespace rns_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rns_msgs::AnnotationModify > {
  static const char* value()
  {
    return "c1b1dd6347d93bcf8dacf5e4166ca3cc";
  }

  static const char* value(const ::rns_msgs::AnnotationModify&) { return value(); }
};

template<>
struct DataType< ::rns_msgs::AnnotationModify > {
  static const char* value()
  {
    return "rns_msgs/AnnotationModify";
  }

  static const char* value(const ::rns_msgs::AnnotationModify&) { return value(); }
};


// service_traits::MD5Sum< ::rns_msgs::AnnotationModifyRequest> should match 
// service_traits::MD5Sum< ::rns_msgs::AnnotationModify > 
template<>
struct MD5Sum< ::rns_msgs::AnnotationModifyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::AnnotationModify >::value();
  }
  static const char* value(const ::rns_msgs::AnnotationModifyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::AnnotationModifyRequest> should match 
// service_traits::DataType< ::rns_msgs::AnnotationModify > 
template<>
struct DataType< ::rns_msgs::AnnotationModifyRequest>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::AnnotationModify >::value();
  }
  static const char* value(const ::rns_msgs::AnnotationModifyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rns_msgs::AnnotationModifyResponse> should match 
// service_traits::MD5Sum< ::rns_msgs::AnnotationModify > 
template<>
struct MD5Sum< ::rns_msgs::AnnotationModifyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::AnnotationModify >::value();
  }
  static const char* value(const ::rns_msgs::AnnotationModifyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::AnnotationModifyResponse> should match 
// service_traits::DataType< ::rns_msgs::AnnotationModify > 
template<>
struct DataType< ::rns_msgs::AnnotationModifyResponse>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::AnnotationModify >::value();
  }
  static const char* value(const ::rns_msgs::AnnotationModifyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RNS_MSGS_MESSAGE_ANNOTATIONMODIFY_H
