// Generated by gencpp from file rns_msgs/AnnotationModifyResponse.msg
// DO NOT EDIT!


#ifndef RNS_MSGS_MESSAGE_ANNOTATIONMODIFYRESPONSE_H
#define RNS_MSGS_MESSAGE_ANNOTATIONMODIFYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rns_msgs
{
template <class ContainerAllocator>
struct AnnotationModifyResponse_
{
  typedef AnnotationModifyResponse_<ContainerAllocator> Type;

  AnnotationModifyResponse_()
    : revision(0)
    , ids()  {
    }
  AnnotationModifyResponse_(const ContainerAllocator& _alloc)
    : revision(0)
    , ids(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _revision_type;
  _revision_type revision;

   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _ids_type;
  _ids_type ids;





  typedef boost::shared_ptr< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AnnotationModifyResponse_

typedef ::rns_msgs::AnnotationModifyResponse_<std::allocator<void> > AnnotationModifyResponse;

typedef boost::shared_ptr< ::rns_msgs::AnnotationModifyResponse > AnnotationModifyResponsePtr;
typedef boost::shared_ptr< ::rns_msgs::AnnotationModifyResponse const> AnnotationModifyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rns_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'rns_msgs': ['/home/joji/iris_ws/src/rns_msgs/msg', '/home/joji/iris_ws/devel/share/rns_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ff0f9b56752fae8d623e57e163fa654";
  }

  static const char* value(const ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ff0f9b56752fae8ULL;
  static const uint64_t static_value2 = 0xd623e57e163fa654ULL;
};

template<class ContainerAllocator>
struct DataType< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rns_msgs/AnnotationModifyResponse";
  }

  static const char* value(const ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int64 revision\n\
\n\
\n\
int64[] ids\n\
\n\
";
  }

  static const char* value(const ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.revision);
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AnnotationModifyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rns_msgs::AnnotationModifyResponse_<ContainerAllocator>& v)
  {
    s << indent << "revision: ";
    Printer<int64_t>::stream(s, indent + "  ", v.revision);
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RNS_MSGS_MESSAGE_ANNOTATIONMODIFYRESPONSE_H
