// Generated by gencpp from file rns_msgs/GetMapContents.msg
// DO NOT EDIT!


#ifndef RNS_MSGS_MESSAGE_GETMAPCONTENTS_H
#define RNS_MSGS_MESSAGE_GETMAPCONTENTS_H

#include <ros/service_traits.h>


#include <rns_msgs/GetMapContentsRequest.h>
#include <rns_msgs/GetMapContentsResponse.h>


namespace rns_msgs
{

struct GetMapContents
{

typedef GetMapContentsRequest Request;
typedef GetMapContentsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMapContents
} // namespace rns_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rns_msgs::GetMapContents > {
  static const char* value()
  {
    return "1b81e9a6831ea1bbddfe4258c942c217";
  }

  static const char* value(const ::rns_msgs::GetMapContents&) { return value(); }
};

template<>
struct DataType< ::rns_msgs::GetMapContents > {
  static const char* value()
  {
    return "rns_msgs/GetMapContents";
  }

  static const char* value(const ::rns_msgs::GetMapContents&) { return value(); }
};


// service_traits::MD5Sum< ::rns_msgs::GetMapContentsRequest> should match 
// service_traits::MD5Sum< ::rns_msgs::GetMapContents > 
template<>
struct MD5Sum< ::rns_msgs::GetMapContentsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::GetMapContents >::value();
  }
  static const char* value(const ::rns_msgs::GetMapContentsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::GetMapContentsRequest> should match 
// service_traits::DataType< ::rns_msgs::GetMapContents > 
template<>
struct DataType< ::rns_msgs::GetMapContentsRequest>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::GetMapContents >::value();
  }
  static const char* value(const ::rns_msgs::GetMapContentsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rns_msgs::GetMapContentsResponse> should match 
// service_traits::MD5Sum< ::rns_msgs::GetMapContents > 
template<>
struct MD5Sum< ::rns_msgs::GetMapContentsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::GetMapContents >::value();
  }
  static const char* value(const ::rns_msgs::GetMapContentsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::GetMapContentsResponse> should match 
// service_traits::DataType< ::rns_msgs::GetMapContents > 
template<>
struct DataType< ::rns_msgs::GetMapContentsResponse>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::GetMapContents >::value();
  }
  static const char* value(const ::rns_msgs::GetMapContentsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RNS_MSGS_MESSAGE_GETMAPCONTENTS_H
