// Generated by gencpp from file rns_msgs/MapCell.msg
// DO NOT EDIT!


#ifndef RNS_MSGS_MESSAGE_MAPCELL_H
#define RNS_MSGS_MESSAGE_MAPCELL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rns_msgs
{
template <class ContainerAllocator>
struct MapCell_
{
  typedef MapCell_<ContainerAllocator> Type;

  MapCell_()
    : ax(0.0)
    , ay(0.0)
    , n(0)
    , visits(0)
    , distance(0.0)
    , weight(0.0)  {
    }
  MapCell_(const ContainerAllocator& _alloc)
    : ax(0.0)
    , ay(0.0)
    , n(0)
    , visits(0)
    , distance(0.0)
    , weight(0.0)  {
  (void)_alloc;
    }



   typedef float _ax_type;
  _ax_type ax;

   typedef float _ay_type;
  _ay_type ay;

   typedef int32_t _n_type;
  _n_type n;

   typedef int32_t _visits_type;
  _visits_type visits;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _weight_type;
  _weight_type weight;





  typedef boost::shared_ptr< ::rns_msgs::MapCell_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rns_msgs::MapCell_<ContainerAllocator> const> ConstPtr;

}; // struct MapCell_

typedef ::rns_msgs::MapCell_<std::allocator<void> > MapCell;

typedef boost::shared_ptr< ::rns_msgs::MapCell > MapCellPtr;
typedef boost::shared_ptr< ::rns_msgs::MapCell const> MapCellConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rns_msgs::MapCell_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rns_msgs::MapCell_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rns_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'rns_msgs': ['/home/joji/iris_ws/src/rns_msgs/msg', '/home/joji/iris_ws/devel/share/rns_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rns_msgs::MapCell_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rns_msgs::MapCell_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rns_msgs::MapCell_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rns_msgs::MapCell_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rns_msgs::MapCell_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rns_msgs::MapCell_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rns_msgs::MapCell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "62ee396d75bc8a98307908aecc949abe";
  }

  static const char* value(const ::rns_msgs::MapCell_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x62ee396d75bc8a98ULL;
  static const uint64_t static_value2 = 0x307908aecc949abeULL;
};

template<class ContainerAllocator>
struct DataType< ::rns_msgs::MapCell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rns_msgs/MapCell";
  }

  static const char* value(const ::rns_msgs::MapCell_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rns_msgs::MapCell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 ax			# accumulated wall X position\n\
float32 ay			# accumulated wall Y position\n\
int32 n				# number of wall occurences\n\
int32 visits		# total number of visits \n\
float32 distance	# array for SDF distance\n\
float32 weight		# array for SDF weight\n\
";
  }

  static const char* value(const ::rns_msgs::MapCell_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rns_msgs::MapCell_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ax);
      stream.next(m.ay);
      stream.next(m.n);
      stream.next(m.visits);
      stream.next(m.distance);
      stream.next(m.weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapCell_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rns_msgs::MapCell_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rns_msgs::MapCell_<ContainerAllocator>& v)
  {
    s << indent << "ax: ";
    Printer<float>::stream(s, indent + "  ", v.ax);
    s << indent << "ay: ";
    Printer<float>::stream(s, indent + "  ", v.ay);
    s << indent << "n: ";
    Printer<int32_t>::stream(s, indent + "  ", v.n);
    s << indent << "visits: ";
    Printer<int32_t>::stream(s, indent + "  ", v.visits);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "weight: ";
    Printer<float>::stream(s, indent + "  ", v.weight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RNS_MSGS_MESSAGE_MAPCELL_H
