// Generated by gencpp from file rns_msgs/MoveToFeedback.msg
// DO NOT EDIT!


#ifndef RNS_MSGS_MESSAGE_MOVETOFEEDBACK_H
#define RNS_MSGS_MESSAGE_MOVETOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rns_msgs/AnnotatedPath.h>

namespace rns_msgs
{
template <class ContainerAllocator>
struct MoveToFeedback_
{
  typedef MoveToFeedback_<ContainerAllocator> Type;

  MoveToFeedback_()
    : recalculation(false)
    , obstacleIndex(0)
    , obstacleDistance(0.0)
    , waypoint(0)
    , moverState(0)
    , msg()
    , path()  {
    }
  MoveToFeedback_(const ContainerAllocator& _alloc)
    : recalculation(false)
    , obstacleIndex(0)
    , obstacleDistance(0.0)
    , waypoint(0)
    , moverState(0)
    , msg(_alloc)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _recalculation_type;
  _recalculation_type recalculation;

   typedef int32_t _obstacleIndex_type;
  _obstacleIndex_type obstacleIndex;

   typedef float _obstacleDistance_type;
  _obstacleDistance_type obstacleDistance;

   typedef int32_t _waypoint_type;
  _waypoint_type waypoint;

   typedef int32_t _moverState_type;
  _moverState_type moverState;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;

   typedef  ::rns_msgs::AnnotatedPath_<ContainerAllocator>  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::rns_msgs::MoveToFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rns_msgs::MoveToFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToFeedback_

typedef ::rns_msgs::MoveToFeedback_<std::allocator<void> > MoveToFeedback;

typedef boost::shared_ptr< ::rns_msgs::MoveToFeedback > MoveToFeedbackPtr;
typedef boost::shared_ptr< ::rns_msgs::MoveToFeedback const> MoveToFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rns_msgs::MoveToFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rns_msgs::MoveToFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rns_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'rns_msgs': ['/home/joji/iris_ws/src/rns_msgs/msg', '/home/joji/iris_ws/devel/share/rns_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rns_msgs::MoveToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rns_msgs::MoveToFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rns_msgs::MoveToFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rns_msgs::MoveToFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rns_msgs::MoveToFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rns_msgs::MoveToFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rns_msgs::MoveToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5d103605c7fc4819d625a164ef95674";
  }

  static const char* value(const ::rns_msgs::MoveToFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5d103605c7fc481ULL;
  static const uint64_t static_value2 = 0x9d625a164ef95674ULL;
};

template<class ContainerAllocator>
struct DataType< ::rns_msgs::MoveToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rns_msgs/MoveToFeedback";
  }

  static const char* value(const ::rns_msgs::MoveToFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rns_msgs::MoveToFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Progress\n\
bool recalculation\n\
int32 obstacleIndex\n\
float32 obstacleDistance\n\
# Current waypoint, if there is a waypoint path\n\
int32 waypoint\n\
# Mover state\n\
int32 moverState\n\
# Message for status update\n\
string msg\n\
# Current path\n\
rns_msgs/AnnotatedPath path\n\
\n\
================================================================================\n\
MSG: rns_msgs/AnnotatedPath\n\
std_msgs/Header header\n\
\n\
# Path request id. \n\
int32 id\n\
# Actual path\n\
rns_msgs/Waypoint[] waypoints\n\
# Should mover take care of waypoint directions\n\
bool useDirections\n\
# If path is reversed\n\
bool reversed\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: rns_msgs/Waypoint\n\
# Desired position\n\
float32 x\n\
float32 y\n\
# desired direction, in radians\n\
float32 angle\n\
# Max velocity for this waypoint, -1 if no limits\n\
float32 maxVelocity\n\
# Max deviation from this waypoint\n\
float32 maxDeviation\n\
# If target position is relevant\n\
bool useDirection\n\
# Max angle deviation\n\
float32 angleDeviation\n\
";
  }

  static const char* value(const ::rns_msgs::MoveToFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rns_msgs::MoveToFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.recalculation);
      stream.next(m.obstacleIndex);
      stream.next(m.obstacleDistance);
      stream.next(m.waypoint);
      stream.next(m.moverState);
      stream.next(m.msg);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rns_msgs::MoveToFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rns_msgs::MoveToFeedback_<ContainerAllocator>& v)
  {
    s << indent << "recalculation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.recalculation);
    s << indent << "obstacleIndex: ";
    Printer<int32_t>::stream(s, indent + "  ", v.obstacleIndex);
    s << indent << "obstacleDistance: ";
    Printer<float>::stream(s, indent + "  ", v.obstacleDistance);
    s << indent << "waypoint: ";
    Printer<int32_t>::stream(s, indent + "  ", v.waypoint);
    s << indent << "moverState: ";
    Printer<int32_t>::stream(s, indent + "  ", v.moverState);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
    s << indent << "path: ";
    s << std::endl;
    Printer< ::rns_msgs::AnnotatedPath_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RNS_MSGS_MESSAGE_MOVETOFEEDBACK_H
