// Generated by gencpp from file rns_msgs/SetJointConfig.msg
// DO NOT EDIT!


#ifndef RNS_MSGS_MESSAGE_SETJOINTCONFIG_H
#define RNS_MSGS_MESSAGE_SETJOINTCONFIG_H

#include <ros/service_traits.h>


#include <rns_msgs/SetJointConfigRequest.h>
#include <rns_msgs/SetJointConfigResponse.h>


namespace rns_msgs
{

struct SetJointConfig
{

typedef SetJointConfigRequest Request;
typedef SetJointConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointConfig
} // namespace rns_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rns_msgs::SetJointConfig > {
  static const char* value()
  {
    return "1c6291a4c108d62355e9249140ae293c";
  }

  static const char* value(const ::rns_msgs::SetJointConfig&) { return value(); }
};

template<>
struct DataType< ::rns_msgs::SetJointConfig > {
  static const char* value()
  {
    return "rns_msgs/SetJointConfig";
  }

  static const char* value(const ::rns_msgs::SetJointConfig&) { return value(); }
};


// service_traits::MD5Sum< ::rns_msgs::SetJointConfigRequest> should match 
// service_traits::MD5Sum< ::rns_msgs::SetJointConfig > 
template<>
struct MD5Sum< ::rns_msgs::SetJointConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::SetJointConfig >::value();
  }
  static const char* value(const ::rns_msgs::SetJointConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::SetJointConfigRequest> should match 
// service_traits::DataType< ::rns_msgs::SetJointConfig > 
template<>
struct DataType< ::rns_msgs::SetJointConfigRequest>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::SetJointConfig >::value();
  }
  static const char* value(const ::rns_msgs::SetJointConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rns_msgs::SetJointConfigResponse> should match 
// service_traits::MD5Sum< ::rns_msgs::SetJointConfig > 
template<>
struct MD5Sum< ::rns_msgs::SetJointConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::SetJointConfig >::value();
  }
  static const char* value(const ::rns_msgs::SetJointConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::SetJointConfigResponse> should match 
// service_traits::DataType< ::rns_msgs::SetJointConfig > 
template<>
struct DataType< ::rns_msgs::SetJointConfigResponse>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::SetJointConfig >::value();
  }
  static const char* value(const ::rns_msgs::SetJointConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RNS_MSGS_MESSAGE_SETJOINTCONFIG_H
