// Generated by gencpp from file rns_msgs/SetMap.msg
// DO NOT EDIT!


#ifndef RNS_MSGS_MESSAGE_SETMAP_H
#define RNS_MSGS_MESSAGE_SETMAP_H

#include <ros/service_traits.h>


#include <rns_msgs/SetMapRequest.h>
#include <rns_msgs/SetMapResponse.h>


namespace rns_msgs
{

struct SetMap
{

typedef SetMapRequest Request;
typedef SetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMap
} // namespace rns_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rns_msgs::SetMap > {
  static const char* value()
  {
    return "a0cab6c54454c8c7895007ac34c24aff";
  }

  static const char* value(const ::rns_msgs::SetMap&) { return value(); }
};

template<>
struct DataType< ::rns_msgs::SetMap > {
  static const char* value()
  {
    return "rns_msgs/SetMap";
  }

  static const char* value(const ::rns_msgs::SetMap&) { return value(); }
};


// service_traits::MD5Sum< ::rns_msgs::SetMapRequest> should match 
// service_traits::MD5Sum< ::rns_msgs::SetMap > 
template<>
struct MD5Sum< ::rns_msgs::SetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::SetMap >::value();
  }
  static const char* value(const ::rns_msgs::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::SetMapRequest> should match 
// service_traits::DataType< ::rns_msgs::SetMap > 
template<>
struct DataType< ::rns_msgs::SetMapRequest>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::SetMap >::value();
  }
  static const char* value(const ::rns_msgs::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rns_msgs::SetMapResponse> should match 
// service_traits::MD5Sum< ::rns_msgs::SetMap > 
template<>
struct MD5Sum< ::rns_msgs::SetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::SetMap >::value();
  }
  static const char* value(const ::rns_msgs::SetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::SetMapResponse> should match 
// service_traits::DataType< ::rns_msgs::SetMap > 
template<>
struct DataType< ::rns_msgs::SetMapResponse>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::SetMap >::value();
  }
  static const char* value(const ::rns_msgs::SetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RNS_MSGS_MESSAGE_SETMAP_H
