// Generated by gencpp from file rns_msgs/SetPose.msg
// DO NOT EDIT!


#ifndef RNS_MSGS_MESSAGE_SETPOSE_H
#define RNS_MSGS_MESSAGE_SETPOSE_H

#include <ros/service_traits.h>


#include <rns_msgs/SetPoseRequest.h>
#include <rns_msgs/SetPoseResponse.h>


namespace rns_msgs
{

struct SetPose
{

typedef SetPoseRequest Request;
typedef SetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPose
} // namespace rns_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rns_msgs::SetPose > {
  static const char* value()
  {
    return "64fa10ed880d9440d76d610062a82bf9";
  }

  static const char* value(const ::rns_msgs::SetPose&) { return value(); }
};

template<>
struct DataType< ::rns_msgs::SetPose > {
  static const char* value()
  {
    return "rns_msgs/SetPose";
  }

  static const char* value(const ::rns_msgs::SetPose&) { return value(); }
};


// service_traits::MD5Sum< ::rns_msgs::SetPoseRequest> should match 
// service_traits::MD5Sum< ::rns_msgs::SetPose > 
template<>
struct MD5Sum< ::rns_msgs::SetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::SetPose >::value();
  }
  static const char* value(const ::rns_msgs::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::SetPoseRequest> should match 
// service_traits::DataType< ::rns_msgs::SetPose > 
template<>
struct DataType< ::rns_msgs::SetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::SetPose >::value();
  }
  static const char* value(const ::rns_msgs::SetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rns_msgs::SetPoseResponse> should match 
// service_traits::MD5Sum< ::rns_msgs::SetPose > 
template<>
struct MD5Sum< ::rns_msgs::SetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rns_msgs::SetPose >::value();
  }
  static const char* value(const ::rns_msgs::SetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rns_msgs::SetPoseResponse> should match 
// service_traits::DataType< ::rns_msgs::SetPose > 
template<>
struct DataType< ::rns_msgs::SetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::rns_msgs::SetPose >::value();
  }
  static const char* value(const ::rns_msgs::SetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RNS_MSGS_MESSAGE_SETPOSE_H
