// Auto-generated. Do not edit!

// (in-package rns_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let MoveToActionGoal = require('./MoveToActionGoal.js');
let MoveToActionResult = require('./MoveToActionResult.js');
let MoveToActionFeedback = require('./MoveToActionFeedback.js');

//-----------------------------------------------------------

class MoveToAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new MoveToActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new MoveToActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new MoveToActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveToAction
    // Serialize message field [action_goal]
    bufferOffset = MoveToActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = MoveToActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = MoveToActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveToAction
    let len;
    let data = new MoveToAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = MoveToActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = MoveToActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = MoveToActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += MoveToActionGoal.getMessageSize(object.action_goal);
    length += MoveToActionResult.getMessageSize(object.action_result);
    length += MoveToActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rns_msgs/MoveToAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b6836f6034d8efdf47971eee8dffb65d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    MoveToActionGoal action_goal
    MoveToActionResult action_result
    MoveToActionFeedback action_feedback
    
    ================================================================================
    MSG: rns_msgs/MoveToActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    MoveToGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: rns_msgs/MoveToGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    geometry_msgs/PoseStamped goal
    # Maximum distance for path search
    float32 maxDistance
    # Minimal distance to be reached
    float32 minDistance
    # Set to true if target orientation is necessary
    bool oriented
    # Set to true if search can enter unknown areas
    bool canVisitUnknown
    # ID of object(s) to be followed
    int64[] objectID
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    ================================================================================
    MSG: rns_msgs/MoveToActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    MoveToResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: rns_msgs/MoveToResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    # Arrival error
    float32 distanceError
    # If task is complete successfully
    bool complete
    
    ================================================================================
    MSG: rns_msgs/MoveToActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    MoveToFeedback feedback
    
    ================================================================================
    MSG: rns_msgs/MoveToFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Progress
    bool recalculation
    int32 obstacleIndex
    float32 obstacleDistance
    # Current waypoint, if there is a waypoint path
    int32 waypoint
    # Mover state
    int32 moverState
    # Message for status update
    string msg
    # Current path
    rns_msgs/AnnotatedPath path
    
    ================================================================================
    MSG: rns_msgs/AnnotatedPath
    std_msgs/Header header
    
    # Path request id. 
    int32 id
    # Actual path
    rns_msgs/Waypoint[] waypoints
    # Should mover take care of waypoint directions
    bool useDirections
    # If path is reversed
    bool reversed
    ================================================================================
    MSG: rns_msgs/Waypoint
    # Desired position
    float32 x
    float32 y
    # desired direction, in radians
    float32 angle
    # Max velocity for this waypoint, -1 if no limits
    float32 maxVelocity
    # Max deviation from this waypoint
    float32 maxDeviation
    # If target position is relevant
    bool useDirection
    # Max angle deviation
    float32 angleDeviation
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveToAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = MoveToActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new MoveToActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = MoveToActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new MoveToActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = MoveToActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new MoveToActionFeedback()
    }

    return resolved;
    }
};

module.exports = MoveToAction;
