// Auto-generated. Do not edit!

// (in-package rns_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MoveToResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.distanceError = null;
      this.complete = null;
    }
    else {
      if (initObj.hasOwnProperty('distanceError')) {
        this.distanceError = initObj.distanceError
      }
      else {
        this.distanceError = 0.0;
      }
      if (initObj.hasOwnProperty('complete')) {
        this.complete = initObj.complete
      }
      else {
        this.complete = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveToResult
    // Serialize message field [distanceError]
    bufferOffset = _serializer.float32(obj.distanceError, buffer, bufferOffset);
    // Serialize message field [complete]
    bufferOffset = _serializer.bool(obj.complete, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveToResult
    let len;
    let data = new MoveToResult(null);
    // Deserialize message field [distanceError]
    data.distanceError = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [complete]
    data.complete = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 5;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rns_msgs/MoveToResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4c6a208ca079fe404bbe7dd5bc64766d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Result
    # Arrival error
    float32 distanceError
    # If task is complete successfully
    bool complete
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveToResult(null);
    if (msg.distanceError !== undefined) {
      resolved.distanceError = msg.distanceError;
    }
    else {
      resolved.distanceError = 0.0
    }

    if (msg.complete !== undefined) {
      resolved.complete = msg.complete;
    }
    else {
      resolved.complete = false
    }

    return resolved;
    }
};

module.exports = MoveToResult;
